### ISSUE TITLE
line 16: wmctrl: command not found

### ISSUE THREAD

**Issue by osuritz** [mezga0153/offscreen-window-restore#1]
I've encountered this bug a few times already and glad that it's not just me. I tried your script on my Ubuntu but I'm getting the following error:

`line 16: wmctrl: command not found`

**Comment by mezga0153** [comment]
hi, you can fix that by installing the wmctrl package in ubuntu:

```
sudo apt-get install wmctrl
```

**Comment by Potherca** [comment]
I thought I'd better comment here before opening a new issue.

When running

    sudo apt-get install wmctl

I get the error 

    E: Unable to locate package wmctl

**Comment by mezga0153** [comment]
you have a typo there - package name is wmctrl, you are missing the r

**Comment by Potherca** [comment]
Doh. Thanks for pointing that out. I'll remove my comments as to not dilute this thread.

Thanks again!
