### ISSUE TITLE
Wrong file content in script

### ISSUE THREAD

**Issue by eiamjw** [mezga0153/offscreen-window-restore#7]
This doesn't work under Ubuntu 16.04. The following error message:

 ./offscreen-window-restore.sh: line 7: syntax error near unexpected token `newline'
./offscreen-window-restore.sh: line 7: `<!DOCTYPE html>'

The file is not a linux script - it's an XML document.

**Comment by mezga0153** [comment]
if you have an xml document you probably downloaded the script improperly, please use git to download.
